# -------------------------------
# Optimizer Settings
# -------------------------------
base_lr: 0.0007
warm_lr: 0.00001
warm_lr_epochs: 1
final_lr: 0.000005
lr_scheduler: "cosine"
weight_decay: 0.1
filter_biases_wd: false
clip_gradient: 0.1

# -------------------------------
# Model Architecture
# -------------------------------
model_name: "vdetr"
num_points: 100000

minkowski: true
mink_syncbn: true
stem_bn: true
voxel_size: 0.02
depth: 34
inplanes: 64
num_stages: 4
use_fpn: true
layer_idx: 0
no_mink_first_pool: true
enc_dim: 256

# Decoder
dec_nlayers: 9
dec_dim: 256
dec_ffn_dim: 256
dec_dropout: 0.1
dec_nhead: 4

rpe_dim: 128
rpe_quant: "bilinear_4_10"
log_scale: 512.0

pos_for_key: false
querypos_mlp: true
q_content: "random"

repeat_num: 5
proj_nohid: true
woexpand_conv: true
share_selfattn: false

# MLP heads
mlp_dropout: 0.3
mlp_norm: "bn1d"
mlp_act: "relu"
mlp_sep: true
nsemcls: -1

# Other model params
preenc_npoints: 4096
nqueries: 1024
is_bilable: true
no_first_repeat: true
use_superpoint: false
axis_align_test: false
iou_type: "diou"
angle_type: ""  # or "world_coords", "object_coords"
use_normals: false
hard_anchor: false

# -------------------------------
# Matcher Loss
# -------------------------------
matcher_giou_cost: 2.0
matcher_cls_cost: 3.0
matcher_center_cost: 1.0
matcher_objectness_cost: 0.0
matcher_size_cost: 0.5
matcher_anglecls_cost: 0.0
matcher_anglereg_cost: 0.5

# -------------------------------
# Loss Weights
# -------------------------------
cls_loss: "focalloss_0.25"
loss_giou_weight: 2.0
loss_sem_cls_weight: 3.0
loss_no_object_weight: 0.0
loss_angle_cls_weight: 0.1
loss_angle_reg_weight: 0.5
loss_center_weight: 1.0
loss_size_weight: 0.5
point_cls_loss_weight: 0.05

# -------------------------------
# Dataset
# -------------------------------
dataset_name: "aicity"
dataset_root_dir: "/perception/dataset/PhysicalAI-SmartSpaces/pcd_dataset_slice_20"
meta_data_dir: null
dataset_num_workers: 16
batchsize_per_gpu: 1
filt_empty: true
merge_cls: true


normal_trans: false

random_fps: true
use_color: true
xyz_color: true
color_mean: -1.0

# -------------------------------
# Training
# -------------------------------
start_epoch: -1
max_epoch: 50
step_epoch: ""
eval_every_epoch: 50
seed: 0

# -------------------------------
# Testing
# -------------------------------
test_only: false
auto_test: false
test_no_nms: false
no_3d_nms: false
rotated_nms: false
nms_iou: 0.25
empty_pt_thre: 5
conf_thresh: 0.0
test_ckpt: ""

angle_nms: false
angle_conf: false
use_old_type_nms: false
no_cls_nms: false
no_per_class_proposal: false
use_cls_confidence_only: false
test_size: false

# -------------------------------
# I/O
# -------------------------------
checkpoint_dir: "./checkpoints/best"
log_every: 10
log_metrics_every: 20
save_separate_checkpoint_every_epoch: 1

# -------------------------------
# Distributed Training
# -------------------------------
ngpus: 1
dist_url: "tcp://localhost:12345"

# -------------------------------
# Weights & Biases (wandb)
# -------------------------------
wandb_activate: false
wandb_entity: null
wandb_project: "best"
wandb_key: "your_wandb_key_here"
